### ISSUE TITLE
Warning: Format set to YAML but input does not start with '---' | But content starts with `---`

### ISSUE THREAD

**Issue by rochacbruno** [sebastienrousseau/frontmatter-gen#9]
Reproducer

```toml
[package]
name = "fg_reproducer"
version = "0.1.0"
edition = "2021"

[dependencies]
frontmatter-gen = { version = "0.0.4", features=["default"] }
log = "0.4"
env_logger = "0.11.5"
```
```rust
use env_logger::{Builder, Env};
use frontmatter_gen::extract;
use log::error;

fn main() {
    let env = Env::default().default_filter_or("warn");
    if let Err(e) = Builder::from_env(env).try_init() {
        error!("Logger already initialized: {}", e);
    }

    let content = "---\ntitle: Not found\n---\n\n<div style=\"text-align:center;\">\n    <img src=\"https://http.cat/images/404.jpg\">\n</div>\n";

    let fm = extract(content).map_err(|e| e.to_string());

    dbg!(fm.unwrap());
}
```
Result
```
[2024-11-23T22:40:22Z WARN  frontmatter_gen::parser] Warning: Format set to YAML but input does not start with '---'
```

```console
$ cargo run
Compiling fg_test v0.1.0 (/home/rochacbruno/Projects/fg_test)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.89s
     Running `target/debug/fg_test`
[2024-11-23T22:40:22Z WARN  frontmatter_gen::parser] Warning: Format set to YAML but input does not start with '---'
[src/main.rs:15:5] fm.unwrap() = (
    Frontmatter(
        {
            "title": String(
                "Not found",
            ),
        },
    ),
    "<div style=\"text-align:center;\">\n    <img src=\"https://http.cat/images/404.jpg\">\n</div>\n",
)

```

```
